name = "MeshTools"
uuid = "f52d8617-ac12-4ead-9403-65bee92ea2d2"
authors = ["Ian Limarta <ian.limarta@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlyIO = "42171d58-473b-503a-8d5f-782019eb09ec"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
